-- ============================================
-- TERRENE — Supabase Database Schema
-- ============================================
-- Run this in Supabase SQL Editor:
-- https://app.supabase.com → your project → SQL Editor → New Query
-- Paste and Run.

-- 1. Products table
CREATE TABLE IF NOT EXISTS products (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        TEXT NOT NULL,
  name        TEXT NOT NULL,
  material    TEXT,
  price       NUMERIC(10,2) NOT NULL DEFAULT 0,
  emoji       TEXT,
  bg          TEXT,
  badge       TEXT,
  active      BOOLEAN NOT NULL DEFAULT true,
  stock       INTEGER NOT NULL DEFAULT 0,
  description TEXT,
  story       TEXT,
  images      JSONB,
  specs       JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Orders table
CREATE TABLE IF NOT EXISTS orders (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        TEXT NOT NULL UNIQUE,
  paypal_order_id TEXT,
  customer_email  TEXT,
  customer_name   TEXT,
  items           JSONB,
  total           NUMERIC(10,2) NOT NULL,
  status          TEXT NOT NULL DEFAULT 'paid',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Settings table (single-row)
CREATE TABLE IF NOT EXISTS settings (
  id                    BIGINT PRIMARY KEY DEFAULT 1,
  storeName             TEXT DEFAULT 'Terrene',
  tagline               TEXT DEFAULT 'Wear the Earth',
  contactEmail          TEXT DEFAULT '',
  freeShippingThreshold INTEGER DEFAULT 50,
  announcement          TEXT DEFAULT '',
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Insert default settings row if not exists
INSERT INTO settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- Insert seed product data (optional — only if you want to pre-populate)
INSERT INTO products (slug, name, material, price, emoji, bg, badge, active, stock, description, story, images, specs) VALUES
('morning-ritual', 'Morning Ritual', 'Coffee Bean & Sandalwood', 22.00, '☕', '#8B6914', 'Bestseller', true, 50,
 'Start each day grounded. Our signature bracelet pairs aromatic coffee beans with warm sandalwood beads.',
 'Every Morning Ritual begins on a small coffee farm where beans are sun-dried for three weeks. Each bean is hand-drilled and strung between sandalwood beads — a material known for its calming, grounding properties.',
 '{"main":"images/products/webp/morning-ritual-main.webp","detail":"images/products/webp/morning-ritual-detail.webp","wear":"images/products/webp/morning-ritual-wear.webp","scene":"images/products/webp/morning-ritual-scene.webp"}',
 '{"materials":"Arabica coffee beans, sandalwood beads, elastic cord","size":"Adjustable 6.5–8 inches","weight":"~15g","care":"Keep dry. Avoid prolonged water exposure.","origin":"Coffee: Colombia | Sandalwood: India | Assembled in USA"}'),
('forest-floor', 'Forest Floor', 'Tagua Nut & Lava Rock', 28.00, '🌰', '#5C4033', NULL, true, 35,
 'Earthy and grounding. Smooth tagua nuts paired with porous lava rock for a tactile experience that connects you to the earth.',
 'Tagua nuts — known as vegetable ivory — have been carved by Amazonian artisans for centuries. We pair them with volcanic lava rock to create a bracelet that feels both ancient and modern.',
 '{"main":"images/products/webp/forest-floor-main.webp","detail":"images/products/webp/forest-floor-detail.webp","wear":"images/products/webp/forest-floor-wear.webp","scene":"images/products/webp/forest-floor-scene.webp"}',
 '{"materials":"Tagua nut beads, lava rock beads, waxed cotton cord","size":"Adjustable 6.5–8 inches","weight":"~18g","care":"Wipe with dry cloth. Store in a cool, dry place.","origin":"Tagua: Ecuador | Lava: Indonesia | Assembled in USA"}'),
('amazon-dawn', 'Amazon Dawn', 'Acai Seed & Coconut Shell', 26.00, '🫐', '#6B8E23', NULL, true, 40,
 'Vibrant and alive. Deep purple acai seeds contrast with natural coconut shell — a bracelet that carries the spirit of the rainforest.',
 'Acai seeds are collected by riverside communities in the Amazon basin. Each tiny seed carries the deep purple hue of the fruit it once protected. Paired with coconut shell, this bracelet tells the story of the rainforest at dawn.',
 '{"main":"images/products/webp/amazon-dawn-main.webp","detail":"images/products/webp/amazon-dawn-detail.webp","wear":"images/products/webp/amazon-dawn-wear.webp","scene":"images/products/webp/amazon-dawn-scene.webp"}',
 '{"materials":"Acai seeds, coconut shell beads, elastic cord","size":"Adjustable 6.5–8 inches","weight":"~12g","care":"Keep dry. Colors may deepen naturally over time.","origin":"Acai: Brazil | Coconut: Philippines | Assembled in USA"}'),
('desert-bloom', 'Desert Bloom', 'Lotus Seed & Terracotta', 24.00, '🪷', '#C67B4B', 'New', true, 30,
 'Delicate and resilient. Lotus seeds meet warm terracotta beads — a bracelet inspired by desert flowers that bloom against all odds.',
 'Lotus seeds can remain viable for centuries, waiting for the right conditions to bloom. We pair these symbols of resilience with hand-formed terracotta beads, celebrating the beauty of patience and timing.',
 '{"main":"images/products/webp/desert-bloom-main.webp","detail":"images/products/webp/desert-bloom-detail.webp","wear":"images/products/webp/desert-bloom-wear.webp","scene":"images/products/webp/desert-bloom-scene.webp"}',
 '{"materials":"Lotus seeds, terracotta beads, elastic cord","size":"Adjustable 6.5–8 inches","weight":"~14g","care":"Fragile — handle with care. Keep dry.","origin":"Lotus: India | Terracotta: Mexico | Assembled in USA"}'),
('ocean-drift', 'Ocean Drift', 'Driftwood Seed & Aquamarine', 30.00, '🌊', '#5F9EA0', NULL, true, 25,
 'Calm and fluid. Weathered driftwood seeds paired with aquamarine chips — a bracelet shaped by water and time.',
 'Driftwood seeds travel ocean currents for months before washing ashore. Each one carries a journey. We pair them with aquamarine — the stone sailors once carried for protection at sea.',
 '{"main":"images/products/webp/ocean-drift-main.webp","detail":"images/products/webp/ocean-drift-detail.webp","wear":"images/products/webp/ocean-drift-wear.webp","scene":"images/products/webp/ocean-drift-scene.webp"}',
 '{"materials":"Driftwood seeds, aquamarine chips, waxed linen cord","size":"Adjustable 6.5–8 inches","weight":"~16g","care":"Avoid saltwater. Wipe with dry cloth.","origin":"Seeds: Pacific Islands | Aquamarine: Brazil | Assembled in USA"}'),
('garden-path', 'Garden Path', 'Mixed Botanicals & Brass', 34.00, '🌸', '#8FBC8F', NULL, true, 20,
 'A curated blend. Mixed seeds, dried botanicals, and brass accents — like walking through a secret garden.',
 'Garden Path is our most eclectic piece. We gather seeds and dried flowers from organic farms, pairing them with warm brass spacers. No two are the same — each is a unique composition of nature''s palette.',
 '{"main":"images/products/webp/garden-path-main.webp","detail":"images/products/webp/garden-path-detail.webp","wear":"images/products/webp/garden-path-wear.webp","scene":"images/products/webp/garden-path-scene.webp"}',
 '{"materials":"Mixed botanical seeds, dried flowers, brass spacers, elastic cord","size":"Adjustable 6.5–8 inches","weight":"~20g","care":"Very delicate. Keep dry. Store flat.","origin":"Various organic farms | Brass: India | Assembled in USA"}')
ON CONFLICT DO NOTHING;

-- Enable Row Level Security (RLS) and create public access policies
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Allow public read access to products
CREATE POLICY "Public read products" ON products
  FOR SELECT USING (true);

-- Allow public insert/update/delete on products (for admin use)
-- In production, you should restrict this with a secret key
CREATE POLICY "Admin write products" ON products
  FOR ALL USING (true) WITH CHECK (true);

-- Allow public read on orders (for admin)
CREATE POLICY "Admin read orders" ON orders
  FOR SELECT USING (true);

-- Allow public insert on orders (for checkout)
CREATE POLICY "Public create orders" ON orders
  FOR INSERT WITH CHECK (true);

-- Allow public update on orders (for admin status changes)
CREATE POLICY "Admin update orders" ON orders
  FOR UPDATE USING (true) WITH CHECK (true);

-- Allow public read/write on settings
CREATE POLICY "Admin read settings" ON settings
  FOR SELECT USING (true);

CREATE POLICY "Admin write settings" ON settings
  FOR ALL USING (true) WITH CHECK (true);
